# Use a Tomcat base image for the runtime environment
FROM tomcat:9.0-jre11-slim

# Remove the default ROOT web application (optional)
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy the WAR file generated by your Jenkins job to Tomcat's webapps directory
COPY /target/maven-web-app.war /usr/local/tomcat/webapps/ROOT.war


# Expose the default Tomcat port (8080)
EXPOSE 8080

# Start Tomcat when the container runs
CMD ["catalina.sh", "run"]

